### ISSUE TITLE
Seems not to work anymore

### ISSUE THREAD

**Issue by markggn** [Confectrician/collect_tb_codes#1]
Changing line 69 to
var Element=document.getElementById('ctl00_divContentSide');
brings back the box, but new tb codes are not added.

**Comment by Confectrician** [comment]
Hi,

Seems my emails are broken too, since i didnt receive any.
I will check this. Give me some time. :)

**Comment by Confectrician** [comment]
So after a short look:
Seems that the Markup and html ids were changed.
I have brought back the Box too now, but i cant verify that the script is not working.

Would be nice to ahve some feedback. Collecting is working fine now for me.
(Tested with Firefox)

**Comment by Confectrician** [comment]
Closed for now, since there was no feedback and it is working again for me.
